---
language: ruby
rvm:
- 2.3.1
- 2.4.1
before_install: gem install bundler -v 1.11.2
deploy:
  provider: rubygems
  api_key:
    secure: wH1kuoIanHWL0ohGKyFtcXDusgR5T5qD2QnaQS9vjIG6a//ClpYpDZ3iSxHG9CkkrbaKJDVhcGsKJOECcQRnLQ2/g9PC84c4tMzfgp3q5w7FdWfxe86diS3sXN4gw6+Xb+KhueOhO6RaghG1BJPBd2kj2G8uw6f/KT+8qOMaS+IRpuW8FkO7x8CZvUSLbzai21kYaneDglb5j/AY/sF2s+jGO/3VPmMjaJCJ7pU84Wqby6PixPMiP2EKVyhx1fD8m8CcPTAfPhiwxq1AkxxFJIkty730ECzwDVfrF9Ph5dcoR57jPliCSctNVREele2Q4ItBxi5Da5U3PiqHYu6AZR4pARoPMaO8m/ZwfvRftzwNDd7jnnkxLgWRRKDofU6wuxB+Jg8V7CbThTXyPFgn8RXYsL4tshOCCmicT8fbKO/f+S21gSQtQI1fZc6dc0WZqRCCY50NLnRH0eAJzXKfQxQ7iuKsF/nfGmZiAmVCZRKWVlGjQ+v5q5erXr+nS9prWotg/CrWiGhPkhHuEj8izBXxclzAuQHGE0H+IRwZFT/7Ym1KUKKhMx5mFRpf4EqLQ+mzIe8+4Ogn8YQclVP/3j14FtGCFiRegqy8SSfsKxTunF6i76Nbdj8v5Pkb0NZzvRjaBkbhvYKIAmLK1GaYC0lQS7gaqXqCRS64XjvAOGQ=
  gem: tableschema
  on:
    tags: true
    repo: frictionlessdata/tableschema-rb
